M48
; DRILL file {KiCad 8.0.5} date 2024-11-13T12:29:45-0600
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-11-13T12:29:45-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X121.31Y-84.345
X127.09Y-84.345
T2
X100.8Y-54.0
X100.8Y-86.75
X192.95Y-54.0
X192.95Y-86.75
M30
